In [1]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

humanCapital = pd.read_excel('Data/SBDC Human Capital Survey Data 4.1.24.xlsx')
hours = pd.read_excel('Data/Consulting Hours.xlsx')
capital = pd.read_excel('Data/Capital Milestones.xlsx')
established = pd.read_excel('Data/Business Established.xlsx')

# Data preprocessing

In [2]:
humanCapital = humanCapital.drop(['ResponseId', 'StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress', 'Duration (in seconds)', 'Finished', 
                                  'RecordedDate', 'RecipientLastName', 'RecipientFirstName', 'RecipientEmail', 'ExternalReference',
                                  'LocationLatitude', 'LocationLongitude', 'DistributionChannel', 'UserLanguage', 'Q_RecaptchaScore'], axis=1)

humanCapital.columns = humanCapital.iloc[0]
humanCapital = humanCapital[1:].reset_index(drop=True)

In [3]:
nDakota = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'North Dakota']
sDakota = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'South Dakota']
iowa = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'The best State (Iowa)']
wyoming = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'Wyoming SBDC Network ']
nebraska = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'Nebraska Business Development Center (NBDC)'].drop(
    ['What state/network are you completing the survey for?'], axis=1)
newMexico = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'New Mexico Small Business Development Center']
kansas = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'Kansas']
montana = humanCapital[humanCapital['What state/network are you completing the survey for?'] == 'Montana']

In [4]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in nebraska.columns if 'Center Information #' in col]))

nebraska_centers = []
for center in centers:
    center_columns = [col for col in nebraska.columns if f'Center Information #{center} ' in col]
    
    center_df = nebraska[center_columns].copy() 
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'Nebraska'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]
        
        globals()[f'nebraska{center}'] = center_df
        nebraska_centers.append(globals()[f'nebraska{center}'])

In [5]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in sDakota.columns if 'Center Information #' in col]))

sDakota_centers = []
for center in centers:
    center_columns = [col for col in sDakota.columns if f'Center Information #{center} ' in col]
    
    center_df = sDakota[center_columns].copy()
    
    if not center_df.isna().all().all(): 

        center_df.loc[:, 'State'] = 'South Dakota'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'sDakota{center}'] = center_df
        sDakota_centers.append(globals()[f'sDakota{center}'])

In [6]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in nDakota.columns if 'Center Information #' in col]))

nDakota_centers = []
for center in centers:
    center_columns = [col for col in nDakota.columns if f'Center Information #{center} ' in col]
    
    center_df = nDakota[center_columns].copy()
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'North Dakota'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'nDakota{center}'] = center_df
        nDakota_centers.append(globals()[f'nDakota{center}'])

In [7]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in iowa.columns if 'Center Information #' in col]))

iowa_centers = []
for center in centers:
    center_columns = [col for col in iowa.columns if f'Center Information #{center} ' in col]
    
    center_df = sDakota[center_columns].copy()
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'Iowa'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'iowa{center}'] = center_df
        iowa_centers.append(globals()[f'iowa{center}'])

In [8]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in wyoming.columns if 'Center Information #' in col]))

wyoming_centers = []
for center in centers:
    center_columns = [col for col in sDakota.columns if f'Center Information #{center} ' in col]
    
    center_df = wyoming[center_columns].copy()
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'Wyoming'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'wyoming{center}'] = center_df
        wyoming_centers.append(globals()[f'wyoming{center}'])

In [9]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in newMexico.columns if 'Center Information #' in col]))

newMexico_centers = []
for center in centers:
    center_columns = [col for col in newMexico.columns if f'Center Information #{center} ' in col]
    
    center_df = newMexico[center_columns].copy()

    if not center_df.isna().all().all():
        center_df['State'] = 'New Mexico'
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]
        
        globals()[f'newMexico{center}'] = center_df
        newMexico_centers.append(center_df)

In [10]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in kansas.columns if 'Center Information #' in col]))

kansas_centers = []
for center in centers:
    center_columns = [col for col in kansas.columns if f'Center Information #{center} ' in col]  # Correct reference here
    
    center_df = kansas[center_columns].copy()
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'Kansas'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'kansas{center}'] = center_df
        kansas_centers.append(globals()[f'kansas{center}'])

In [11]:
centers = sorted(set([col.split(' ')[2].replace('#', '') for col in montana.columns if 'Center Information #' in col]))

montana_centers = []
for center in centers:
    center_columns = [col for col in newMexico.columns if f'Center Information #{center} ' in col]
    
    center_df = montana[center_columns].copy()
    
    if not center_df.isna().all().all(): 
        center_df.loc[:, 'State'] = 'Montana'
        
        center_df = center_df[['State'] + [col for col in center_df.columns if col != 'State']]

        globals()[f'montana{center}'] = center_df
        montana_centers.append(globals()[f'montana{center}'])

In [12]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

state_center_lists = [
    nebraska_centers, sDakota_centers, nDakota_centers, iowa_centers, 
    wyoming_centers, newMexico_centers, kansas_centers, montana_centers
]
state_names = [
    'Nebraska', 'South Dakota', 'North Dakota', 'Iowa', 
    'Wyoming', 'New Mexico', 'Kansas', 'Montana'
]

data = []

for state_centers, state_name in zip(state_center_lists, state_names):
    center_number = 1
    for center_df in state_centers:
        ft_staff_cols = [col for col in center_df.columns if 'Number of FT Staff' in col]
        pt_staff_cols = [col for col in center_df.columns if 'Number of PT Staff' in col]
        consultant_cols = [col for col in center_df.columns if 'Number of contracted consultants' in col]
        counseling_time_cols = [col for col in center_df.columns if 'Total contact, prep, travel time for 2023' in col]
        population_cols = [col for col in center_df.columns if 'What is the population of the region' in col]
        location_cols = [col for col in center_df.columns if 'Is the center location rural or urban' in col]
        hr_support_cols = [col for col in center_df.columns if 'HR paperwork for employees/review and reconciliation of invoices for consultants' in col]
        client_cols = [col for col in center_df.columns if 'Number of clients' in col]
        program_related_time_cols = [col for col in center_df.columns if 'Total hours spent on other program-related activity' in col]
        employees_reporting_cols = [col for col in center_df.columns if 'Does the Center Director have employees reporting directly to them' in col]

        total_ft_staff = sum([pd.to_numeric(center_df[col], errors='coerce').sum() for col in ft_staff_cols]) if ft_staff_cols else 0
        total_pt_staff = sum([pd.to_numeric(center_df[col], errors='coerce').sum() * 0.5 for col in pt_staff_cols]) if pt_staff_cols else 0
        total_consultants = sum([pd.to_numeric(center_df[col], errors='coerce').sum() for col in consultant_cols]) if consultant_cols else 0
        total_staff = total_ft_staff + total_pt_staff + total_consultants
        
        total_counseling_time = sum([pd.to_numeric(center_df[col], errors='coerce').sum() for col in counseling_time_cols]) if counseling_time_cols else 0
        
        population = sum([pd.to_numeric(center_df[col].astype(str).str.replace(',', ''), errors='coerce').sum() for col in population_cols]) if population_cols else 0
        
        location = center_df[location_cols].iloc[0] if location_cols and not center_df[location_cols].isna().all().all() else ''
        is_urban = 1 if isinstance(location, str) and 'urban' in location.lower() else 0
        
        hr_support = 1 if center_df[hr_support_cols].eq('Yes').any().any() else 0
        num_clients = sum([pd.to_numeric(center_df[col], errors='coerce').sum() for col in client_cols]) if client_cols else 0
        program_related_time = sum([pd.to_numeric(center_df[col], errors='coerce').sum() for col in program_related_time_cols]) if program_related_time_cols else 0
        has_employees_reporting = 1 if center_df[employees_reporting_cols].eq('Yes').any().any() else 0

        data.append({
            'State': state_name,
            'Center Number': center_number,
            'Total Staff': total_staff,
            'Population': population,
            'Is Urban': is_urban,
            'HR Support': hr_support,
            'Total Counseling Time': total_counseling_time,
            'Number of Clients': num_clients,
            'Program-Related Activity Time': program_related_time,
            'Has Employees Reporting': has_employees_reporting
        })

        center_number += 1

center_analysis = pd.DataFrame(data)

numeric_cols = center_analysis.columns.difference(['State'])
center_analysis[numeric_cols] = center_analysis[numeric_cols].apply(pd.to_numeric, errors='coerce')

predictors = ['Total Staff', 'Population', 'Is Urban', 'HR Support', 'Number of Clients', 
              'Program-Related Activity Time', 'Has Employees Reporting', 'Responsible for Paperwork']

# for predictor in predictors:
#     plt.figure(figsize=(8, 6))
    
#     plt.scatter(center_analysis[predictor], center_analysis['Total Counseling Time'], alpha=0.5)
    
#     plt.title(f'Relationship between {predictor} and Total Counseling Time')
#     plt.xlabel(predictor)
#     plt.ylabel('Total Counseling Time')
    
#     plt.show()

center_analysis.insert(2, 'Center Name', pd.Series(['Omaha', 'Lincoln', 'Kearney', 'Wayne', 'North Platte', 'Scottsbluff', 'Chadron'] + [np.nan] * (len(center_analysis) - 7)))

center_analysis.to_excel('Data/Center Analysis.xlsx', index=False)

# Counseling Hours Modeling

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error


center_analysis = center_analysis[(center_analysis['Total Staff'] > 0) & 
                                  (center_analysis['Number of Clients'] > 0) & 
                                  (center_analysis['Total Counseling Time'] > 0)]

center_analysis.index = np.arange(1, len(center_analysis) + 1)

X = center_analysis[['Total Staff', 'Population', 'Is Urban', 'HR Support', 'Number of Clients', 
                     'Has Employees Reporting']].values
y = center_analysis['Total Counseling Time'].values

center_analysis = pd.DataFrame(data)

numeric_cols = center_analysis.columns.difference(['State'])
center_analysis[numeric_cols] = center_analysis[numeric_cols].apply(pd.to_numeric, errors='coerce')

center_analysis = center_analysis[(center_analysis['Total Staff'] > 0) & 
                                  (center_analysis['Number of Clients'] > 0) & 
                                  (center_analysis['Total Counseling Time'] > 0)]

center_analysis.index = np.arange(1, len(center_analysis) + 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(n_estimators=290, random_state=42)
rf_model.fit(X, y)

predicted_counseling_times = rf_model.predict(X)

center_analysis['Predicted Counseling Time'] = predicted_counseling_times

center_analysis['Expected Hours per Consultant'] = center_analysis['Predicted Counseling Time'] / center_analysis['Total Staff']
center_analysis['Expected Hours per Client'] = center_analysis['Predicted Counseling Time'] / center_analysis['Number of Clients']

center_analysis['Expected Hours per Consultant'] = center_analysis['Expected Hours per Consultant'].apply(lambda x: max(x, 0))
center_analysis['Expected Hours per Client'] = center_analysis['Expected Hours per Client'].apply(lambda x: max(x, 0))

mse = mean_squared_error(y, predicted_counseling_times)
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error: {rmse}")

r2 = r2_score(y, predicted_counseling_times)
print(f"R² score: {r2}")

Root Mean Squared Error: 199.90293632651554
R² score: 0.9537785571477073

# Ideal number of staff

In [14]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


center_analysis = pd.DataFrame(data)
center_analysis = center_analysis[(center_analysis['Total Staff'] > 0) &
                                  (center_analysis['Number of Clients'] > 0) &
                                  (center_analysis['Total Counseling Time'] > 0)]

X_staff = center_analysis[['Total Counseling Time', 'Population', 'Is Urban', 'HR Support', 'Number of Clients', 'Has Employees Reporting']]
y_staff = center_analysis['Total Staff']

log_transformer = FunctionTransformer(np.log1p, validate=True)
preprocessor = ColumnTransformer(
    transformers=[('log', log_transformer, ['Population', 'Total Counseling Time'])],
    remainder='passthrough'
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(n_estimators=200, max_depth=20, max_features='sqrt', min_samples_split=2, min_samples_leaf=1, random_state=42))
])
pipeline.fit(X_staff, y_staff)

adjustments = np.linspace(-10, 10, 10) 
ideal_staff_per_center = []

for index, row in center_analysis.iterrows():
    adjusted_predictions = []
    for adj in adjustments:
        adjusted_features = row.copy()
        adjusted_features['Total Counseling Time'] *= (1 + adj / 100)
        adjusted_features['Population'] *= (1 + adj / 100)
        adjusted_features['Number of Clients'] *= (1 + adj / 100)

        adjusted_data = pd.DataFrame([adjusted_features], columns=X_staff.columns)
        
        adjusted_prediction = pipeline.predict(adjusted_data)
        adjusted_predictions.append(adjusted_prediction[0])

    ideal_staff = np.mean(adjusted_predictions)
    ideal_staff_per_center.append(ideal_staff)

center_analysis['Ideal Staff'] = ideal_staff_per_center
center_analysis

,State,Center Number,Total Staff,Population,Is Urban,HR Support,Total Counseling Time,Number of Clients,Program-Related Activity Time,Has Employees Reporting,Ideal Staff
0,Nebraska,1,5.0,811625,0,0,857.00,424,832.00,1,4.85925
1,Nebraska,2,1.5,503116,0,1,363.00,106,125.00,1,2.16500
2,Nebraska,3,1.0,244314,0,1,525.00,83,120.00,0,1.28375
3,Nebraska,4,1.0,254971,0,0,392.00,86,480.00,0,1.63850
4,Nebraska,5,1.0,56691,0,0,95.00,40,20.00,0,1.00075
5,Nebraska,6,1.0,80866,0,0,62.00,52,226.00,0,1.01950
6,Nebraska,7,1.5,25078,0,1,231.00,28,72.00,1,1.43750
7,South Dakota,1,2.0,104677,0,1,703.53,170,0.00,1,1.92350
8,South Dakota,2,1.0,67488,0,0,341.97,98,0.00,0,1.01775
9,South Dakota,3,3.0,197874,0,1,837.55,346,0.00,1,2.64275
10,South Dakota,4,3.0,276730,0,1,2736.61,449,0.00,0,2.98050
11,South Dakota,5,2.0,109432,0,0,449.97,84,0.00,0,1.59550
12,South Dakota,6,2.0,130466,0,1,663.25,95,0.00,1,1.92525
13,North Dakota,1,2.0,283651,0,1,1895.75,518,1086.75,1,2.80375
14,North Dakota,2,1.0,92609,0,0,927.25,240,460.25,0,1.50400
15,North Dakota,3,0.5,37193,0,0,524.25,62,613.50,0,0.75825
16,North Dakota,4,1.0,98042,0,0,947.00,165,842.00,0,1.15150
17,North Dakota,5,2.5,54204,0,1,1236.75,392,773.00,0,2.32025
18,North Dakota,6,0.5,41986,0,0,1061.50,131,1102.25,0,1.16900
19,North Dakota,7,0.5,5681,0,0,349.25,44,871.50,0,0.70550
20,North Dakota,8,1.0,165895,0,0,566.00,235,203.00,0,1.50500
21,Iowa,1,2.0,104677,0,1,703.53,170,0.00,1,1.92350
22,Iowa,2,1.0,67488,0,0,341.97,98,0.00,0,1.01775
23,Iowa,3,3.0,197874,0,1,837.55,346,0.00,1,2.64275
24,Iowa,4,3.0,276730,0,1,2736.61,449,0.00,0,2.98050
25,Iowa,5,2.0,109432,0,0,449.97,84,0.00,0,1.59550
26,Iowa,6,2.0,130466,0,1,663.25,95,0.00,1,1.92525
27,Wyoming,1,7.0,578803,0,1,4930.54,1398,748.00,0,6.02275
28,New Mexico,1,2.0,67666,0,1,716.00,1010,0.00,1,2.07450
29,New Mexico,2,1.0,26780,0,1,250.00,612,0.00,0,1.03625
30,New Mexico,3,2.0,50322,0,1,634.00,546,0.00,1,1.88475
31,New Mexico,4,2.0,155956,0,1,554.00,2887,0.00,1,2.19050
32,New Mexico,5,3.5,120675,0,1,946.00,1124,0.00,1,2.80000
33,New Mexico,6,1.0,68797,0,1,835.00,869,0.00,0,1.38675
34,New Mexico,7,1.0,19444,0,1,491.00,713,0.00,0,1.03125
35,New Mexico,8,1.0,34405,0,1,697.00,1387,0.00,0,1.41150
36,New Mexico,9,2.0,110737,0,1,890.00,1488,0.00,1,2.48950
37,New Mexico,10,2.0,60578,0,1,355.00,1348,0.00,1,1.97975
38,New Mexico,11,4.0,827522,0,1,1662.00,4722,0.00,1,4.46875
39,New Mexico,12,4.0,236698,0,1,789.00,1409,0.00,1,3.05425
40,New Mexico,13,2.0,63561,0,1,389.00,532,0.00,1,1.93725
41,New Mexico,14,1.0,47338,0,1,337.00,548,0.00,0,1.15400
43,New Mexico,16,2.0,72101,0,1,820.00,1896,0.00,1,2.15850
44,New Mexico,17,2.0,88864,0,1,722.00,1257,0.00,1,2.11350
45,New Mexico,18,2.0,60275,0,1,678.00,579,0.00,1,1.97950
46,Kansas,1,1.0,189893,0,1,875.00,150,322.00,0,1.21725
47,Kansas,2,9.0,813299,0,0,4169.00,1074,7572.00,1,7.27125
48,Kansas,3,4.0,268888,0,0,1846.00,451,4996.00,1,4.04450
49,Kansas,4,7.0,181960,0,0,1180.00,249,1152.00,1,4.37775
50,Kansas,5,4.5,712190,0,0,3403.00,615,9430.00,1,5.20225
51,Kansas,6,5.5,394932,0,0,2727.00,524,5970.00,1,5.07775
52,Kansas,7,6.0,376718,0,0,1404.00,282,2373.00,1,5.39300
53,Montana,1,2.0,221648,0,1,1349.00,225,223.00,1,2.56750
54,Montana,2,1.0,36593,0,1,615.00,94,23.00,0,1.00625
55,Montana,3,1.0,146777,0,1,704.00,176,0.00,0,1.12875
56,Montana,4,1.5,91073,0,1,960.00,119,35.50,1,1.74550
57,Montana,5,2.5,131099,0,1,898.00,239,38.50,1,2.39100
58,Montana,6,1.0,34896,0,1,465.00,78,21.00,0,1.03625
59,Montana,7,1.5,87342,0,1,180.00,80,16.00,1,1.54825
60,Montana,8,1.0,175834,0,1,796.00,219,0.00,0,1.17975
61,Montana,9,1.0,37916,0,1,133.00,31,18.00,0,1.01850
62,Montana,10,1.5,192969,0,1,750.00,298,6.00,1,2.24300